"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const persona_1 = require("./persona");
const curso_1 = require("./curso");
const modulo_1 = require("./modulo");
const leccion_1 = require("./leccion");
const evaluacion_1 = require("./evaluacion");
const pregunta_1 = require("./pregunta");
const respuesta_1 = require("./respuesta");
const angel = new persona_1.Persona('Ángel', 'Villalba');
const curso = new curso_1.Curso('c1', 'Curso de JavaScript', angel, 20);
const mike = new persona_1.Persona('Mike', 'Kozinsky');
const charly = new persona_1.Persona('Charly', 'Falco');
curso.matricularAlumno('1', mike);
curso.matricularAlumno('2', charly);
const modulo1 = new modulo_1.Modulo('m1', 'Introducción a JS');
const leccion1 = new leccion_1.Leccion('l1', 'Tipos de datos', 5);
const leccion2 = new leccion_1.Leccion('l2', 'Variables', 20);
const evaluacion1 = new evaluacion_1.Evaluacion('e1', 'Tipos de datos y variables');
const respuesta1 = new respuesta_1.Respuesta('r1', 'Si', true);
const respuesta2 = new respuesta_1.Respuesta('r2', 'No', false);
const respuesta3 = new respuesta_1.Respuesta('r3', 'Si', false);
const respuesta4 = new respuesta_1.Respuesta('r4', 'No', true);
const pregunta1 = new pregunta_1.Pregunta('p1', '¿La variable "var titulo" está bien declarada?', [respuesta1, respuesta2]);
const pregunta2 = new pregunta_1.Pregunta('p2', '¿La variable "var 3titulo" está bien declarada?', [respuesta3, respuesta4]);
evaluacion1.agregarPregunta(pregunta1);
evaluacion1.agregarPregunta(pregunta2);
modulo1.agregarContenido(leccion1);
modulo1.agregarContenido(leccion2);
modulo1.agregarContenido(evaluacion1);
curso.agregarModulo(modulo1);
const modulo2 = new modulo_1.Modulo('m2', 'JS en el navegador');
const leccion3 = new leccion_1.Leccion('l3', 'Objeto window', 30);
modulo2.agregarContenido(leccion3);
curso.agregarModulo(modulo2);
const info = curso.getInformacionCurso();
console.log(info);
